image: docker:latest

services:
  - docker:dind

build_and_push_sqlite:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t toggl-bridge-sqlite .
    - docker tag toggl-bridge-sqlite "$CI_REGISTRY"/plaza-project/bridges/toggl-bridge/toggl-bridge-sqlite:$CI_COMMIT_SHA
    - docker push "$CI_REGISTRY"/plaza-project/bridges/toggl-bridge/toggl-bridge-sqlite:$CI_COMMIT_SHA
  only:
    - develop
    - master

build_and_push_postgresql:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t toggl-bridge-postgresql -f Dockerfile.postgresql .
    - docker tag toggl-bridge-postgresql "$CI_REGISTRY"/plaza-project/bridges/toggl-bridge/toggl-bridge-postgresql:$CI_COMMIT_SHA
    - docker push "$CI_REGISTRY"/plaza-project/bridges/toggl-bridge/toggl-bridge-postgresql:$CI_COMMIT_SHA
  only:
    - develop
    - master
